### ISSUE TITLE
Fix pricing logic w.r.t. non-integer values

### ISSUE THREAD

**Issue by evinism** [willfulbard/larkcamp_reg#31]
Right now, if you use a non-integer value for a donation to Lark Camp, the pricing logic errors out. 

We should:
1. Handle partial dollars in a sane manner.
2. Be able to have some sort of validation to insure that a user can't put in a number with precision > 2.

**Comment by evinism** [comment]
Okay I'm gonna make an executive decision and say that people can only donate integer amounts woodlands and LTA because I don't want to deal w. the interaction of json logic and floats, esp. cross language.

**Comment by evinism** [comment]
(This also applies to t-shirts btw)

**Comment by brsaylor** [comment]
Integers only makes sense to me.

**Comment by evinism** [comment]
Fixed in above!
