### ISSUE TITLE
Add logic/option for 50% deposit

### ISSUE THREAD

**Issue by willfulbard** [willfulbard/larkcamp_reg#38]
Show that you need to have the 50% deposit in by 2 weeks:

![Screen Shot 2019-10-27 at 10 40 02 PM](https://user-images.githubusercontent.com/15619556/67654439-d3ce1b80-f90a-11e9-9c15-84e274f78d7d.png)

**Comment by evinism** [comment]
QQ on this. Just to ensure I'm not off by 1 day here, if today is the 29th of October, for payment purposes, 2 weeks from now would be the 12th of November, right?

**Comment by evinism** [comment]
okay also, i want to give a total rather than "50% due" because that's clearer, but that brings up the question of whether 50% is due INCLUDING donations to the woodlands / LTA. Can you confirm the answer is "lol no we won't require them to deposit 50% of their donations to LTA or the woodlands"?

**Comment by willfulbard** [comment]
1. It's a soft deadline, so I wouldn't stress over the off-by-1.  Usually we just send an email at that point.  Maybe just fudge it in favor of the camper by adding a day?
1. It's actually only 50% of tuition only.  In the latest code I have separated the tuition and the food.  I'll ship what I have so you can see it.

**Comment by willfulbard** [comment]
- meals: https://github.com/willfulbard/larkcamp_reg/blob/master/public/php/RegValueFormatter.php#L188

- tuition: https://github.com/willfulbard/larkcamp_reg/blob/master/public/php/RegValueFormatter.php#L170

**Comment by willfulbard** [comment]
I'm adding a commit that will split up the pricing logic and should make this easier.
