### ISSUE TITLE
Implement dependent fields

### ISSUE THREAD

**Issue by willfulbard** [willfulbard/larkcamp_reg#5]
Certain fields should only show up as a result of other fields being used.  For example - Type of meal should only show up if you are buying meals.

https://react-jsonschema-form.readthedocs.io/en/latest/dependencies/#property-dependencies

**Comment by evinism** [comment]
starting work in https://github.com/willfulbard/larkcamp_reg/pull/10

**Comment by evinism** [comment]
Closing after implementing dependent fields:
- [x] Accomodations
- [x] Meals
